export const tableData = [
    {
      invoiceNo: "12345",
      customerName: "Shubh Agrahari",
      licenseNo: "ABCD1234",
      stopLocation: "Mumbai",
      totalAmount: "$80",
      loadNo: "XY7890",
      emptyMiles: "60 Miles",
      loadedMiles: "40 Miles",
      factoringCompany: "Factory A",
      grossRevenue: "$100",
      dueDate: "2024-04-30",
      invoice: "$750"
    },
    {
      invoiceNo: "56789",
      customerName: "Ansh Gupta",
      licenseNo: "ABCD1234",
      stopLocation: "Mumbai",
      totalAmount: "$80",
      loadNo: "XY7890",
      emptyMiles: "60 Miles",
      loadedMiles: "40 Miles",
      factoringCompany: "Factory B",
      grossRevenue: "$100",
      dueDate: "2024-05-15",
      invoice: "$750"
    },
    {
        invoiceNo: "01234",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory C",
        grossRevenue: "$100",
        dueDate: "2024-06-17",
        invoice: "$750"
      },
      {
        invoiceNo: "45678",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory D",
        grossRevenue: "$100",
        dueDate: "2024-05-25",
        invoice: "$750"
      },
      {
        invoiceNo: "89012",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory E",
        grossRevenue: "$100",
        dueDate: "2024-09-10",
        invoice: "$750"
      },
      {
        invoiceNo: "23456",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory F",
        grossRevenue: "$100",
        dueDate: "2024-10-16",
        invoice: "$750"
      },
      {
        invoiceNo: "67890",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory G",
        grossRevenue: "$100",
        dueDate: "2024-07-18",
        invoice: "$750"
      },
      {
        invoiceNo: "09876",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory H",
        grossRevenue: "$100",
        dueDate: "2024-08-12",
        invoice: "$750"
      },
      {
        invoiceNo: "65432",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory H",
        grossRevenue: "$100",
        dueDate: "2024-05-09",
        invoice: "$750"
      },
      {
        invoiceNo: "62109",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory I",
        grossRevenue: "$100",
        dueDate: "2024-07-21",
        invoice: "$750"
      },
      {
        invoiceNo: "69876",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory J",
        grossRevenue: "$100",
        dueDate: "2024-08-22",
        invoice: "$750"
      },
      {
        invoiceNo: "34621",
        customerName: "Agrahari Shubh",
        licenseNo: "ABCD1234",
        stopLocation: "Mumbai",
        totalAmount: "$80",
        loadNo: "XY7890",
        emptyMiles: "60 Miles",
        loadedMiles: "40 Miles",
        factoringCompany: "Factory K",
        grossRevenue: "$100",
        dueDate: "2024-08-13",
        invoice: "$750"
      },
    // Add more rows as needed
  ];
